elemento de lsita

In [10]:
def es_primo(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            return False
    return True

numeros_primos = []
contador = 2
while len(numeros_primos) < 10:
    if es_primo(contador):
        numeros_primos.append(contador)
    contador += 1

print("Los primeros 10 números primos son:", numeros_primos)
print()
print (numeros_primos[[0:3]])




SyntaxError: invalid syntax (1210913536.py, line 18)

In [18]:
lista_prueba = [1,2,3]
lista_2 = [lista_prueba,4,5]
print(lista_2[0][2][3][1])

lista_prueba



3


In [32]:
entero = 5  #int
entero /= 3 # entero = entero / 3   #float
entero = str(entero)    #str
type(entero)
print(entero)
entero += "1"  
print(entero)

palabra = "CASA"
LISTA_TIPO = (1, "PYTHON", 5.3)
print (LISTA_TIPO)

type(LISTA_TIPO[0])
type(LISTA_TIPO[2])

1.6666666666666667
1.66666666666666671
(1, 'PYTHON', 5.3)


float

In [41]:
import numpy as np

# Crear un array de 1 dimensión
arr1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:")
print(arr1d)

# Crear un array de 2 dimensiones
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray 2D:")
print(arr2d)

# Sumar todos los elementos del array
suma_total = np.sum(arr1d)
print("\nSuma total de elementos en el array 1D:", suma_total)

# Calcular la media de los elementos del array
media = np.mean(arr1d)
print("Media de elementos en el array 1D:", media)

# Calcular la transpuesta del array 2D
transpuesta = np.transpose(arr2d)
print("\nTranspuesta del array 2D:")
print(transpuesta)


Array 1D:
[1 2 3 4 5]

Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma total de elementos en el array 1D: 15
Media de elementos en el array 1D: 3.0

Transpuesta del array 2D:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
%whos

Variable         Type        Data/Info
--------------------------------------
LISTA_TIPO       tuple       n=3
arr1d            ndarray     5: 5 elems, type `int32`, 20 bytes
arr2d            ndarray     3x3: 9 elems, type `int32`, 36 bytes
contador         int         30
entero           str         1.66666666666666671
es_primo         function    <function es_primo at 0x0000023CFACAA2A0>
lista_2          list        n=3
lista_prueba     list        n=3
media            float64     3.0
numeros_primos   list        n=10
palabra          str         CASA
suma_total       int32       15
transpuesta      ndarray     3x3: 9 elems, type `int32`, 36 bytes


In [37]:
del numpy

In [55]:
vector = np.arange(start = 2, stop = 9)
print (vector)



[2 3 4 5 6 7 8]


NameError: name 'vectpr' is not defined

In [79]:
print(lista_prueba)
print (type(lista_prueba))
lista_prueba.append(0)
array_prueba = np.array(lista_prueba)
print (array_prueba)
type(array_prueba)
array_prueba = np.append(array_prueba, 0)
print(array_prueba % 2 )


[1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
<class 'list'>
[1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [66]:
%who

LISTA_TIPO	 arr1d	 arr2d	 array_prueba	 contador	 entero	 es_primo	 lista_2	 lista_prueba	 
media	 np	 numeros_primos	 palabra	 suma_total	 transpuesta	 vector	 


In [82]:
def funcion_none():
    return None

print (funcion_none())

None


In [94]:
array = np.arange(0,20).reshape(2,10)
mask = (((array % 2) == 0) & ((array % 5) == 0))
array[mask]

array([ 0, 10])